---
apiVersion: v1
kind: Secret
metadata:
  name: {{ secret_name }}
  namespace: {{ namespace }}
  annotations:
    vault-uri: {{ vault_addr }}ui/vault/secrets/{{ vault_engine }}/show{{ vault_path|with_leading_slash }}
data:
  {% for (key, secret) in encoded_data -%}
  {{ key }}: {{ secret }}
  {% endfor %}
