[package]
name = "vault"
version = "0.1.0"
authors = ["Benn Sundsrud <benn.sundsrud@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.16"
failure = "0.1.5"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
chrono = "0.4.6"
url = "1.7.2"
lazy_static = "1.3.0"
